name: E2e test workflow

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  kind:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: generate tools version
        run: |
          mkdir tests
          cd tests
          echo 'helm 3.7.1' > .tool-versions
          echo '' > example.yaml

      - name: setup helm
        uses: pixelfederation/gh-action-asdf/install@v2.0.0
        with:
          directory: tests

      - name: chech helm version
        working-directory: tests
        run: |
          which helm
          helm version

      - uses: helm/kind-action@v1.3.0

      - name: Check cluster
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          kubectl config view --raw > ./tests/.kubeconfig

      - name: add helm repo
        working-directory: tests
        run: |
          helm repo add nginx-stable https://helm.nginx.com/stable
          helm search repo nginx-stable/nginx-ingress

      - name: Helm upgrade
        id: helm-upgrade
        uses: pixelfederation/gh-action-helm/upgrade@main
        with:
          dir: tests
          namespace: test
          release: "nginx-deploy"
          chart: "nginx-stable/nginx-ingress"
          version: "0.13.2"
          wait: true
          dryrun: false
          atomic: true
          kubeconfig: .kubeconfig
          files: |
            example.yaml
          set: |
            buildLabels.foo | bar

      - name: Print kubectl deploy
        run: |
          kubectl -n test get deploy
          kubectl -n test get pods

      - name: Print helm deploy
        working-directory: tests
        run:
          helm -n test list
