name: Local devel workflow

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: generate tools version
        run: |
          echo 'helm 3.7.2' > .tool-versions
          echo '' > example.yaml

      - name: setup helm
        uses: pixelfederation/gh-action-asdf/install@v2.0.0

      - name: check helm
        run: |
          which helm
          helm version
          helm repo add bitnami https://charts.bitnami.com/bitnami
          touch foobar.yaml buz.yaml
          kubectl create ns nginx || true

      - name: Set variable
        run: echo '::set-output name=JUST_VARIABLE::myvar'
        id: justvar

      - name: Helm upgrade
        id: helm-upgrade
        uses: ./upgrade
        with:
          namespace: nginx
          release: nginx
          chart: bitnami/nginx
          version: 13.1.0
          wait: true
          dryrun: false
          atomic: true
          timeout: 100
          set: |
            service.type | ClusterIP
            commonLabels.testlabel | tombo
            commonAnnotations.testAnnotation | ${{ steps.justvar.outputs.JUST_VARIABLE }}
            replicaCount | 3
          files: |
            foobar.yaml
            buz.yaml

      - name: Helm upgrade 2
        id: helm-upgrade2
        uses: ./upgrade
        with:
          namespace: nginx
          release: foobar
          chart: bitnami/nginx
          version: 13.1.0
          wait: true
          dryrun: false
          atomic: true
          timeout: 100
          set: |
            service.type | ClusterIP
            commonLabels.testlabel | tombo
            commonAnnotations.testAnnotation | ${{ steps.justvar.outputs.JUST_VARIABLE }}
            replicaCount | 3

      - name: Helm upgrade 3
        id: helm-upgrade3
        uses: ./upgrade
        with:
          namespace: nginx
          release: nginx-buz
          chart: bitnami/nginx
          version: 13.1.0
          wait: true
          dryrun: false
          atomic: true
          timeout: 100
          set: |
            service.type | ClusterIP
            commonLabels.testlabel | tombo
            commonAnnotations.testAnnotation | ${{ steps.justvar.outputs.JUST_VARIABLE }}
            replicaCount | 3

  clean:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Helm version
        id: helm-version
        run: |
          helm version --client

      - name: Set variable
        run: echo '::set-output name=JUST_VARIABLE::myvar'
        id: justvar

      - name: Helm clenup
        id: helm-cleanup
        uses: ./cleanup
        with:
          namespace: nginx
          regexp: "^(tombo|foobar|nginx).*"
          excludes: |
            .*buz.*
