name: Local devel workflow

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: generate tools version
        run: |
          echo 'helm 3.7.2' > .tool-versions
          echo '' > example.yaml

      - name: setup helm
        uses: pixelfederation/gh-action-asdf/install@v2.0.0

      - name: check helm
        run: |
          which helm
          helm version
          helm repo add nginx-stable https://helm.nginx.com/stable
          helm search repo nginx-stable/nginx-ingress
          touch foobar.yaml buz.yaml

      - name: Set variable
        run: echo '::set-output name=JUST_VARIABLE::myvar'
        id: justvar

      - name: Helm upgrade
        id: helm-upgrade
        uses: ./upgrade
        with:
          namespace: test
          release: nginx-deploy
          chart: nginx-stable/nginx-ingress
          version: 0.13.2
          wait: false
          dryrun: true
          atomic: false
          kubeconfig: /root/.kube/config
          set: |
            controller.image.tag | tombo
            controller.ingressClass | ${{ steps.justvar.outputs.JUST_VARIABLE }}
          files: |
            foobar.yaml
            buz.yaml

  clean:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Helm version
        id: helm-version
        run: |
          helm version --client

      - name: Set variable
        run: echo '::set-output name=JUST_VARIABLE::myvar'
        id: justvar

      - name: Helm clenup
        id: helm-cleanup
        uses: ./cleanup
        with:
          kubeconfig: /root/.kube/config
          namespace: echoheaders
          regexp: "^(tombo|kombo).*"
          excludes: |
            .*bla.*
            .*foo.*
